import type { CSSProperties } from 'react';

/** Ancho máximo compartido: barra superior + contenido (alineados). */
export const CRM_SHELL_MAX_WIDTH_PX = 1320;

/**
 * Tokens de estilo del panel admin (objetos `CSSProperties` para inline styles).
 * Convención: `--ink`, `--purple`, etc. vienen de `:root` en `index.css`.
 */
export const crm = {
  layoutRoot: {
    minHeight: '100dvh',
    display: 'flex',
    flexDirection: 'column' as const,
    fontFamily: "'Instrument Sans', sans-serif",
    background: '#e5dfd5',
    backgroundImage:
      'radial-gradient(ellipse 90% 60% at 100% -10%, rgba(96, 62, 249, 0.09) 0%, transparent 55%),' +
      'radial-gradient(ellipse 70% 45% at 0% 110%, rgba(45, 106, 79, 0.06) 0%, transparent 50%),' +
      'linear-gradient(180deg, #ebe5db 0%, #dfd8cc 100%)',
  },

  topBar: {
    position: 'sticky' as const,
    top: 0,
    zIndex: 40,
    borderBottom: '1px solid rgba(26,16,40,0.08)',
    background: 'rgba(255,255,255,0.82)',
    backdropFilter: 'blur(14px)',
  },
  topBarInner: {
    maxWidth: CRM_SHELL_MAX_WIDTH_PX,
    margin: '0 auto',
    padding: '10px clamp(12px, 2.4vw, 28px)',
  },
  brandCluster: {
    display: 'flex',
    alignItems: 'baseline',
    gap: 8,
    flexShrink: 0,
  },
  brandMark: {
    fontFamily: "'Fraunces', serif",
    fontSize: 20,
    fontWeight: 700,
    color: 'var(--ink)',
    letterSpacing: '-0.03em',
  },
  brandSub: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: 'var(--ink-muted)',
  },

  segmentRail: {
    display: 'flex',
    justifyContent: 'center',
    width: '100%',
  },
  segmentTrack: {
    display: 'flex',
    flexWrap: 'nowrap' as const,
    justifyContent: 'flex-start',
    gap: 4,
    padding: 4,
    borderRadius: 14,
    background: 'rgba(26,16,40,0.06)',
    border: '1px solid rgba(26,16,40,0.06)',
    width: '100%',
    boxSizing: 'border-box' as const,
    minWidth: 0,
  },
  segmentBtn: (active: boolean): CSSProperties => ({
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: '1 1 0',
    minWidth: 0,
    gap: 6,
    padding: '8px 6px',
    borderRadius: 10,
    border: 'none',
    cursor: 'pointer',
    fontSize: 'clamp(11px, 1.65vw, 13px)',
    fontWeight: 600,
    letterSpacing: '-0.01em',
    transition: 'background .15s, color .15s, box-shadow .15s',
    background: active ? '#ffffff' : 'transparent',
    color: active ? 'var(--ink)' : 'var(--ink-muted)',
    boxShadow: active ? '0 1px 3px rgba(26,16,40,0.08)' : 'none',
    overflow: 'hidden',
  }),
  segmentIcon: { fontSize: 15, lineHeight: 1 },
  segmentLabel: {
    display: 'block',
    minWidth: 0,
    width: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    textAlign: 'center' as const,
  },

  userCluster: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  /** Nombre del usuario staff junto a «Ver sitio» */
  staffNameInHeader: {
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--ink-soft)',
    letterSpacing: '-0.02em',
    maxWidth: 280,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    flexShrink: 1,
    minWidth: 0,
  },
  topLinkBtn: {
    fontSize: 13,
    fontWeight: 600,
    padding: '8px 12px',
    borderRadius: 9,
    border: '1px solid rgba(26,16,40,0.12)',
    background: '#fff',
    color: 'var(--ink-soft)',
    cursor: 'pointer',
  },
  topDangerBtn: {
    fontSize: 13,
    fontWeight: 600,
    padding: '8px 12px',
    borderRadius: 9,
    border: 'none',
    background: 'transparent',
    color: 'var(--ink-muted)',
    cursor: 'pointer',
    textDecoration: 'underline',
    textUnderlineOffset: 3,
  },

  mainStage: {
    flex: 1,
    width: '100%',
    maxWidth: CRM_SHELL_MAX_WIDTH_PX,
    margin: '0 auto',
    padding: '20px clamp(12px, 2.4vw, 28px) 40px',
    boxSizing: 'border-box' as const,
  },
  contentCard: {
    background: '#fff',
    borderRadius: 16,
    border: '1px solid rgba(26,16,40,0.07)',
    boxShadow: '0 18px 50px rgba(26,16,40,0.07), 0 1px 0 rgba(255,255,255,0.9) inset',
    padding: 'clamp(20px, 4vw, 36px)',
    minHeight: 320,
  },

  /* Section list + headers */
  sectionHead: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 16,
    marginBottom: 28,
    paddingBottom: 22,
    borderBottom: '1px solid rgba(26,16,40,0.07)',
  },
  sectionHeadText: { flex: '1 1 240px', minWidth: 0 },
  pageKicker: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.14em',
    textTransform: 'uppercase' as const,
    color: 'var(--ink-muted)',
    marginBottom: 6,
  },
  pageTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: 'clamp(22px, 4vw, 28px)',
    fontWeight: 700,
    color: 'var(--ink)',
    letterSpacing: '-0.03em',
    lineHeight: 1.2,
    marginBottom: 6,
  },
  pageSubtitle: {
    fontSize: 14,
    color: 'var(--ink-muted)',
    lineHeight: 1.55,
    margin: 0,
    maxWidth: 52 * 16,
  },

  primaryBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 18px',
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    background: 'var(--ink)',
    color: '#fff',
    flexShrink: 0,
    boxShadow: '0 2px 8px rgba(26,16,40,0.15)',
  },

  list: { display: 'flex', flexDirection: 'column' as const, gap: 8 },
  listCard: {
    display: 'flex',
    alignItems: 'flex-start',
    flexWrap: 'wrap' as const,
    gap: 12,
    padding: '14px 16px',
    borderRadius: 12,
    border: '1px solid rgba(26,16,40,0.08)',
    background: '#faf9f7',
    transition: 'background .15s, border-color .15s',
  },
  listEmoji: {
    width: 44,
    height: 44,
    borderRadius: 11,
    background: '#fff',
    border: '1px solid rgba(26,16,40,0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
    flexShrink: 0,
  },
  listBody: {
    flex: '1 1 200px',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 3,
  },
  listTitle: { fontSize: 15, fontWeight: 600, color: 'var(--ink)' },
  listMeta: { fontSize: 13, color: 'var(--ink-muted)' },
  listActions: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 8,
    marginLeft: 'auto',
    alignItems: 'center',
  },

  chipBtn: {
    padding: '6px 12px',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    border: '1px solid rgba(26,16,40,0.12)',
    background: '#fff',
    color: 'var(--ink-soft)',
    cursor: 'pointer',
  },
  chipBtnDanger: {
    borderColor: 'rgba(192,57,43,0.22)',
    background: '#fff8f7',
    color: '#9b2c20',
  },

  /* Full-screen form (modal page) */
  formBackdrop: {
    position: 'fixed' as const,
    inset: 0,
    zIndex: 100,
    background: 'rgba(18, 14, 28, 0.48)',
    backdropFilter: 'blur(10px)',
    display: 'flex',
    alignItems: 'stretch',
    justifyContent: 'center',
    padding: 0,
  },
  formShell: {
    width: '100%',
    maxWidth: 840,
    margin: '0 auto',
    background: '#fdfcfa',
    display: 'flex',
    flexDirection: 'column' as const,
    minHeight: '100%',
    maxHeight: '100%',
    boxShadow: '0 0 0 1px rgba(26,16,40,0.06)',
  },
  formShellDesktop: {
    marginTop: 24,
    marginBottom: 24,
    minHeight: 0,
    borderRadius: 16,
    border: '1px solid rgba(26,16,40,0.08)',
    maxHeight: 'calc(100dvh - 48px)',
    overflow: 'hidden',
    boxShadow: '0 24px 80px rgba(0,0,0,0.16)',
  },
  formHeader: {
    flexShrink: 0,
    padding: '16px 20px',
    borderBottom: '1px solid rgba(26,16,40,0.08)',
    background: '#fff',
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 12,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  formHeaderLeft: {
    display: 'flex',
    gap: 12,
    alignItems: 'flex-start',
    flex: '1 1 200px',
    minWidth: 0,
  },
  formBackBtn: {
    flexShrink: 0,
    padding: '8px 12px',
    borderRadius: 9,
    border: '1px solid rgba(26,16,40,0.12)',
    background: '#fff',
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--ink-soft)',
    cursor: 'pointer',
  },
  formTitleBlock: { minWidth: 0 },
  formTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: 20,
    fontWeight: 700,
    color: 'var(--ink)',
    letterSpacing: '-0.02em',
    marginBottom: 2,
    lineHeight: 1.25,
  },
  formSubtitle: { fontSize: 13, color: 'var(--ink-muted)', margin: 0, lineHeight: 1.45 },
  formHeaderActions: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: 8,
    alignItems: 'center',
    flexShrink: 0,
  },
  formScroll: {
    flex: 1,
    minHeight: 0,
    overflowY: 'auto' as const,
    padding: '20px 22px max(28px, env(safe-area-inset-bottom, 0px))',
    WebkitOverflowScrolling: 'touch' as const,
    overscrollBehavior: 'contain' as const,
    scrollBehavior: 'smooth' as const,
  },

  /** Agrupa campos del formulario en tarjetas con título */
  formSection: {
    marginBottom: 22,
    padding: '18px 20px 20px',
    background: '#fff',
    borderRadius: 14,
    border: '1px solid rgba(26,16,40,0.07)',
    boxShadow: '0 4px 24px rgba(26,16,40,0.04)',
  },
  formSectionHead: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: '1px solid rgba(26,16,40,0.06)',
  },
  formSectionTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: '-0.02em',
    color: 'var(--ink)',
    margin: 0,
    lineHeight: 1.3,
  },
  formSectionAction: { flexShrink: 0 },
  formSectionBody: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  formFooterNote: {
    flexShrink: 0,
    padding: '12px 20px',
    borderTop: '1px solid rgba(26,16,40,0.07)',
    background: '#fff',
    fontSize: 13,
    color: '#c0392b',
  },

  formField: { marginBottom: 15 },
  label: {
    display: 'block',
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--ink-soft)',
    marginBottom: 5,
  },
  hint: {
    fontSize: 12,
    color: 'var(--ink-muted)',
    marginTop: 4,
    lineHeight: 1.4,
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid rgba(26,16,40,0.14)',
    fontSize: 14,
    outline: 'none',
    color: 'var(--ink)',
    boxSizing: 'border-box' as const,
    background: '#fff',
  },
  select: {
    width: '100%',
    padding: '10px 12px',
    borderRadius: 10,
    border: '1px solid rgba(26,16,40,0.14)',
    fontSize: 14,
    background: '#fff',
    cursor: 'pointer',
    color: 'var(--ink)',
  },
  divider: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    margin: '20px 0 16px',
  },
  dividerText: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
    color: 'var(--ink-faint)',
  },
  speakerCard: {
    background: '#fff',
    borderRadius: 11,
    border: '1px solid rgba(26,16,40,0.1)',
    padding: '14px 16px',
    marginBottom: 10,
  },
  addSpeakerBtn: {
    fontSize: 12,
    fontWeight: 600,
    padding: '7px 13px',
    borderRadius: 8,
    background: 'rgba(96,62,249,0.08)',
    color: 'var(--purple)',
    border: '1px solid rgba(96,62,249,0.2)',
    cursor: 'pointer',
  },
  removeSpeakerBtn: {
    fontSize: 12,
    fontWeight: 600,
    padding: '4px 10px',
    borderRadius: 100,
    background: '#fff5f5',
    color: '#c0392b',
    border: '1px solid rgba(192,57,43,0.2)',
    cursor: 'pointer',
  },
  secondaryBtn: {
    padding: '9px 16px',
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    border: '1px solid rgba(26,16,40,0.14)',
    background: '#fff',
    color: 'var(--ink-muted)',
    cursor: 'pointer',
  },
  saveBtn: {
    padding: '9px 20px',
    borderRadius: 10,
    fontSize: 14,
    fontWeight: 600,
    border: 'none',
    cursor: 'pointer',
    background: 'var(--purple)',
    color: '#fff',
    boxShadow: '0 2px 8px rgba(96,62,249,0.3)',
  },
  formError: { margin: 0, flex: 1 },
  emptyWrap: {
    textAlign: 'center' as const,
    padding: '40px 20px',
    borderRadius: 12,
    border: '1px dashed rgba(26,16,40,0.15)',
    background: '#faf9f7',
  },
  emptyTitle: {
    fontFamily: "'Fraunces', serif",
    fontSize: 18,
    fontWeight: 700,
    color: 'var(--ink)',
    marginBottom: 6,
  },
  emptyText: { fontSize: 14, color: 'var(--ink-muted)', lineHeight: 1.55, margin: 0 },
  spinnerWrap: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 20px',
  },
  spinner: {
    width: 36,
    height: 36,
    borderRadius: '50%',
    border: '3px solid var(--border-warm)',
    borderTopColor: 'var(--purple)',
    animation: 'spin 0.75s linear infinite',
  },
};
