import type { Evento, Charla, Empleo } from './types';

export const EVENTOS: Evento[] = [
  {
    id: 'ia-negocios',
    emoji: '🤖',
    day: '18', month: 'ABR',
    tagLabel: 'Charla', tagType: 'p',
    title: 'IA en los Negocios: Del Hype a la Realidad',
    date: 'Jueves 18 de Abril · 18:30hs',
    location: 'Auditorio UCEMA, Reconquista 775',
    desc: 'Cómo las empresas líderes integran IA en sus modelos de negocio. Casos reales y debate abierto.',
    speakerInitials: 'MG',
    speakerName: 'Martín González',
    speakerRole: 'CTO · TechAR',
  },
  {
    id: 'fundraising',
    emoji: '💰',
    day: '25', month: 'ABR',
    tagLabel: 'Workshop', tagType: 'g',
    title: 'Fundraising para Startups: cómo levantar tu primera ronda',
    date: 'Viernes 25 de Abril · 17:00hs',
    location: 'Sala Conferencias B, UCEMA',
    desc: 'El proceso completo: desde preparar el pitch hasta negociar términos con inversores.',
    speakerInitials: 'LP',
    speakerName: 'Laura Pérez',
    speakerRole: 'Partner · InvertAR VC',
  },
  {
    id: 'global',
    emoji: '🌎',
    day: '08', month: 'MAY',
    tagLabel: 'Panel', tagType: 'o',
    title: 'Expandir al Mundo: startups argentinas con alcance global',
    date: 'Jueves 8 de Mayo · 18:00hs',
    location: 'Auditorio UCEMA, Reconquista 775',
    desc: 'Fundadores que escalaron desde Argentina al mundo. Qué aprendieron y cómo fue el camino.',
    speakerInitials: 'RD',
    speakerName: 'Rodrigo Díaz',
    speakerRole: 'Co-founder · Nuvem',
  },
  {
    id: 'hackathon',
    emoji: '⚡',
    day: '15', month: 'MAY',
    tagLabel: 'Hackathon', tagType: 'p',
    title: 'Xplora Hackathon 2025: tecnología con impacto social',
    date: '15–16 de Mayo · 9:00hs · 48hs',
    location: 'Campus UCEMA',
    desc: '48 horas para construir soluciones a problemáticas reales. Mentores, sponsors y premios.',
    speakerInitials: 'XU',
    speakerName: 'Equipo Xplora',
    speakerRole: 'Organización',
  },
];

export const CHARLAS: Charla[] = [
  {
    id: 'lean-startup',
    emoji: '🎯',
    date: '15 de Marzo, 2025',
    title: 'Lean Startup: Validar antes de construir',
    speakerInitials: 'SC',
    speakerName: 'Sofía Castillo · CEO Startify',
    tagLabel: 'Lean Startup', tagType: 'g',
    about: 'Uno de los errores más comunes es construir durante meses algo que nadie necesita. Sofía compartió cómo aplicaron Lean en Startify: cómo identificaron el problema real, construyeron su MVP y pivotaron 3 veces antes de encontrar el product-market fit.',
    topics: [
      'Qué es un MVP y cómo construirlo en 2 semanas',
      'Técnicas de validación con usuarios reales',
      'Cómo pivotar sin perder el foco',
      'El papel del feedback continuo en el desarrollo de producto',
    ],
    duration: '1h 20 min',
    attendees: '87 personas',
    speakerBio: 'CEO y Co-founder de Startify, plataforma de educación emprendedora con +80.000 usuarios en Latinoamérica. Licenciada en Administración (UCEMA, 2018). Ex-analista en McKinsey.',
    whyXplora: 'Sofía es egresada de UCEMA y desde que fundó Startify mantiene un vínculo activo con la universidad. Xplora le da la oportunidad de devolver a la comunidad que la formó, compartiendo aprendizajes reales con quienes están empezando.',
  },
  {
    id: 'fintech',
    emoji: '💳',
    date: '22 de Febrero, 2025',
    title: 'Fintech en Argentina: Oportunidades y regulación',
    speakerInitials: 'AV',
    speakerName: 'Andrés Vidal · Dir. Lemoncash',
    tagLabel: 'Fintech', tagType: 'p',
    about: 'El ecosistema fintech argentino atraviesa una transformación. Andrés exploró las oportunidades y los desafíos regulatorios que enfrentan quienes quieren construir en este espacio.',
    topics: ['El mapa del fintech en Argentina', 'Marco regulatorio actual', 'Oportunidades no explotadas', 'Casos de éxito locales'],
    duration: '1h 10 min',
    attendees: '72 personas',
    speakerBio: 'Director de Producto en Lemoncash. Economista (UBA). Anteriormente en Ualá y Naranja X.',
    whyXplora: 'Andrés cree en conectar a la próxima generación de builders con el ecosistema financiero real, sin filtros.',
  },
  {
    id: 'impacto',
    emoji: '🌱',
    date: '10 de Febrero, 2025',
    title: 'Startups de impacto: hacer el bien y ser rentable',
    speakerInitials: 'MR',
    speakerName: 'Micaela Rivas · Impacto ARG',
    tagLabel: 'Impacto', tagType: 'g',
    about: 'Cómo construir un negocio que genere impacto real sin sacrificar la rentabilidad. Micaela compartió su experiencia fundando Impacto ARG.',
    topics: ['Modelos de negocio de impacto', 'Métricas sociales y financieras', 'Inversores de impacto', 'Casos B Corp en Argentina'],
    duration: '55 min',
    attendees: '64 personas',
    speakerBio: 'Fundadora de Impacto ARG. Magíster en Desarrollo Sostenible (UTDT). Ex UNICEF Argentina.',
    whyXplora: 'Micaela quiere que más jóvenes consideren el impacto como parte central de su modelo de negocio desde el día uno.',
  },
  {
    id: 'logistica',
    emoji: '📦',
    date: '28 de Noviembre, 2024',
    title: 'Logística e-commerce: de 0 a escala en Argentina',
    speakerInitials: 'FP',
    speakerName: 'Federico Peralta · OCA E-commerce',
    tagLabel: 'E-commerce', tagType: 'o',
    about: 'La logística es uno de los cuellos de botella más frecuentes en e-commerce. Federico explicó cómo resolverlo a escala.',
    topics: ['Errores comunes en logística', 'Elegir operador logístico', 'Tecnología aplicada', 'Internacionalización'],
    duration: '1h 05 min',
    attendees: '58 personas',
    speakerBio: 'Head of E-commerce en OCA. 8 años en logística y fulfillment. Speaker en e-commerce Expo.',
    whyXplora: 'Quiere acercar el mundo operativo a los estudiantes, muchas veces alejados de los desafíos reales del negocio.',
  },
  {
    id: 'product',
    emoji: '🧠',
    date: '14 de Noviembre, 2024',
    title: 'Product thinking: diseñar para el usuario real',
    speakerInitials: 'IV',
    speakerName: 'Ignacio Vera · PM en Naranja X',
    tagLabel: 'Producto', tagType: 'p',
    about: 'Una charla sobre cómo hacer producto centrado en el usuario, con herramientas y metodologías aplicadas en Naranja X.',
    topics: ['Jobs To Be Done', 'Discovery vs Delivery', 'Cómo priorizar features', 'Métricas de producto'],
    duration: '1h 15 min',
    attendees: '79 personas',
    speakerBio: 'Product Manager en Naranja X. Ex-UX Designer. Speaker habitual en comunidades de producto latinoamericanas.',
    whyXplora: 'Cree que el pensamiento de producto es una de las habilidades más valiosas que un emprendedor puede desarrollar.',
  },
  {
    id: 'fundador',
    emoji: '🚀',
    date: '05 de Octubre, 2024',
    title: 'Cómo pasé de estudiante a fundador en 18 meses',
    speakerInitials: 'TS',
    speakerName: 'Tomás Silva · Founder Flowit',
    tagLabel: 'Fundador', tagType: 'g',
    about: 'Tomás contó su historia: cómo pasó de la idea al primer cliente, los errores que cometió y qué haría diferente.',
    topics: ['Encontrar la idea', 'Primeros clientes sin producto', 'Equipo inicial', 'Las 3 cosas que nadie te cuenta'],
    duration: '1h 00 min',
    attendees: '94 personas',
    speakerBio: 'Fundador de Flowit, herramienta de automatización para PYMEs. Licenciado en Sistemas UCEMA, 2023.',
    whyXplora: 'Tomás es ex-miembro de Xplora. Volvió a dar su charla como forma de devolver lo que el club le dio.',
  },
];

export const EMPLEOS: Empleo[] = [
  { id: '1', emoji: '🏦', title: 'Analista Financiero Jr.', company: 'Banco Galicia', location: 'Buenos Aires', type: 'Full-time', typeTag: 'g', area: 'Finanzas' },
  { id: '2', emoji: '🚀', title: 'Product Manager Trainee', company: 'Mercado Libre', location: 'CABA', type: 'Full-time', typeTag: 'g', area: 'Tech' },
  { id: '3', emoji: '📊', title: 'Consultor de Estrategia', company: 'McKinsey & Company', location: 'Buenos Aires', type: 'Part-time', typeTag: 'o', area: 'Strategy' },
  { id: '4', emoji: '💳', title: 'Business Analyst — Fintech', company: 'Ualá', location: 'CABA', type: 'Full-time', typeTag: 'g', area: 'Finanzas' },
  { id: '5', emoji: '🌱', title: 'Pasante — Sustentabilidad', company: 'YPF', location: 'Buenos Aires', type: 'Pasantía', typeTag: 'p', area: 'Strategy' },
  { id: '6', emoji: '🤖', title: 'Data Scientist Jr.', company: 'Naranja X', location: 'Córdoba / Remoto', type: 'Remoto', typeTag: 'n', area: 'Tech' },
];
